
//Url
loginUrl=https://www.saucedemo.com/

//Users
valid.username=standard_user
valid.password=secret_sauce
locked.username=locked_out_user
invalid.username=wrong_user
invalid.password=wrong_password
error.message.invalid=Epic sadface: Username and password do not match any user in this service
error.message.locked=Epic sadface: Sorry, this user has been locked out.

//Inventory_Url
inventory.url=inventory.html
