
//Url
loginUrl=https://www.saucedemo.com/

//Users
valid.username=standard_user
valid.password=secret_sauce
locked.username=locked_out_user
invalid.username=wrong_user
invalid.password=wrong_password

//Inventory_Url
inventory.url=inventory.html


//Login.Error.Messages
error.message.one=Epic sadface: Username and password do not match any user in this service
error.message.two=sadface: Sorry, this user has been locked out.
